package uk.co.myspots.model

import spray.httpx.SprayJsonSupport
import spray.json._


//TODO: UserId should come from url, tags should be generated by Description

case class Spot(link: String, title: String, created: Long, userId: String, lastAccess: Long, tags: List[String])
{
  def id = Md5.md5hash1(userId + link).take(6)
}

case class User(firstName: String, lastName: String, created: Long, userId: String)

object RestApiJsonProtocol extends DefaultJsonProtocol with SprayJsonSupport {

  implicit val spotFormat= jsonFormat6(Spot)
  implicit val userFormat = jsonFormat4(User)
}



