package uk.co.myspots.model

import spray.httpx.SprayJsonSupport
import spray.json._


//TODO: aadd method Clone UserId should come from url, tags should be generated by Description

case class Spot(link: String, description: String, created: Long, lastAccess: Long)
{
  def id(userId: String) = Md5.md5hash1(userId + link).take(6)

  def tags = description.split("\\s+").filter(_.startsWith("#")).map(_.substring(1))

}

case class User(firstName: String, lastName: String, created: Long, userId: String)

object RestApiJsonProtocol extends DefaultJsonProtocol with SprayJsonSupport {

  implicit val spotFormat= jsonFormat4(Spot)
  implicit val userFormat = jsonFormat4(User)
}



